### ISSUE TITLE
Water-level-prediction project enquiry

### ISSUE THREAD

**Issue by ah-ke** [htrieu93/Water-level-prediction#1]
Sorry to interrupt. I would like to enquire about the src/modelling/train.py file for the Water-level-prediction project in your github which doesn't seem to be very complete. For example, I can't find the definition of LSTM_model, GRU_model, BiLSTM_model. Please, can you provide a complete code just for research and reference.

**Comment by htrieu93** [comment]
Hi, sorry for the confusion. You can find the 3 models in this directory /src/modelling/model.py. The complete code can be found under the /src folder. However, I have not got the time to fully automated the models yet.

**Comment by ah-ke** [comment]
thank you



---Original---
From: "Hieu ***@***.***&gt;
Date: Fri, Apr 19, 2024 04:25 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [htrieu93/Water-level-prediction] Water-level-prediction projectenquiry (Issue #1)




 
Hi, sorry for the confusion. You can find the 3 models in this directory /src/modelling/model.py. The complete code can be found under the /src folder. However, I have not got the time to fully automated the models yet.
